name: RN version tester for SVG

on:
  workflow_dispatch:

jobs:
  build_android:
    name: Test Android app
    runs-on: ubuntu-latest
    strategy:
      matrix:
        working-directory: ['0.71', '0.70', '0.69', '0.68', '0.67', '0.66', '0.65', '0.64']
      fail-fast: false
    concurrency:
      group: build_android_svg-${{ matrix.working-directory }}
      cancel-in-progress: true
    steps:
      - name: Create react app
        run: npx react-native init app --skip-install --version ${{ matrix.working-directory }}
      - name: Install Svg
        working-directory: app
        run: yarn add github:software-mansion/react-native-svg#main
      - name: Build Android app
        working-directory: app/android
        run: ./gradlew assembleDebug --console=plain
  
  build_ios:
    name: Test iOS app
    runs-on: macos-12
    strategy:
      matrix:
        working-directory: ['0.71', '0.70', '0.69', '0.68', '0.67', '0.66', '0.65', '0.64']
      fail-fast: false
    concurrency:
      group: build_ios-svg-${{ matrix.working-directory }}
      cancel-in-progress: true
    steps:
      - name: Create react app
        run: npx react-native init app --skip-install --version ${{ matrix.working-directory }}
      - name: Install Svg
        working-directory: app
        run: yarn add github:software-mansion/react-native-svg#main
      - name: Install pods
        working-directory: app/ios
        run: pod install
      - name: Build iOS app
        working-directory: app
        run: npx react-native run-ios --simulator='iPhone 14'
