name: RN version tester for Svg from branch

on:
  workflow_dispatch:

env:
  SVG_BRANCH: "@wolewicki/bring-071-to-examples"

jobs:
  build_android:
    name: Test Android app
    runs-on: ubuntu-latest
    strategy:
      matrix:
        working-directory: ['0.70', '0.69', '0.68', '0.67', '0.66', '0.65', '0.64']
      fail-fast: false
    concurrency:
      group: build_android_rea2-${{ matrix.working-directory }}
      cancel-in-progress: true
    steps:
      - name: Create react app
        run: npx react-native init app --version ${{ matrix.working-directory }}
      - name: Install Svg
        working-directory: app
        run: yarn add github:software-mansion/react-native-svg#${{ env.SVG_BRANCH }}
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.13
        with:
          cmake-version: '3.8.x'
      - name: Build Android app
        working-directory: app/android
        run: ./gradlew assembleDebug --console=plain
  
  build_ios:
    name: Test iOS app
    runs-on: macos-12
    strategy:
      matrix:
        working-directory: ['0.70', '0.69', '0.68', '0.67', '0.66', '0.65', '0.64']
      fail-fast: false
    concurrency:
      group: build_ios-rea2-${{ matrix.working-directory }}
      cancel-in-progress: true
    steps:
      - name: Create react app
        run: npx react-native init app --version ${{ matrix.working-directory }}
      - name: Install Svg
        working-directory: app
        run: yarn add github:software-mansion/react-native-svg#${{ env.SVG_BRANCH }}
      - name: Install pods
        working-directory: app/ios
        run: pod install
      - name: Build iOS app
        working-directory: app
        run: npx react-native run-ios
